fs = require("fs")
fse = require("fs-extra")
dir = "template"
fs.mkdirSync(dir) unless fs.existsSync(dir)
fs.renameSync("electron", "#{dir}/electron")
fs.renameSync("app", "#{dir}/app")
fs.renameSync("web", "#{dir}/web")
fs.renameSync(".gitignore", "#{dir}/.gitignore")
fs.renameSync("package.json", "#{dir}/package.json")
require("am-dev/app/copy_template")
fs.renameSync("#{dir}/.gitignore", ".gitignore")
fs.renameSync("#{dir}/package.json", "package.json")
fse.removeSync("node_modules/am-dev/template/app/")
fse.removeSync("node_modules/am-dev/template/electron/")
fse.removeSync("node_modules/am-dev/template/web/")
console.log "fin"
